### ISSUE TITLE
use unique subject lines

### ISSUE THREAD

**Issue by willkg** [marco-c/missing_symbols#7]
This repository has code that generates the "Weekly report of modules with missing symbols in crash reports" emails. These emails get sent to the stability mailing list which is a Google Group:

https://groups.google.com/a/mozilla.org/g/stability

The problem is that all of them end up in the same thread which is now 79 messages long, difficult to find specific messages, and takes a long time to render in the interface. It'd be better if the messages didn't end up in the same thread but rather each had a separate thread.

I'm pretty sure we can change the subject to be unique and that'll break the threading. For example, we could add the date it was rendered as YYYY-MM-DD to the end.

**Comment by willkg** [comment]
If someone gives me a :+1: on adjusting the subject line as suggested, I will make a PR.

**Comment by marco-c** [comment]
@willkg sounds good to me!
